import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import Database from 'better-sqlite3';
import Stripe from 'stripe';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename);
const app=express(),PORT=Number(process.env.PORT||3000),ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'arena43',BASE_URL=process.env.BASE_URL||`http://localhost:${PORT}`,DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data');
const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
fs.mkdirSync(DATA_DIR,{recursive:true}); const db=new Database(path.join(DATA_DIR,'arena43.db')); db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY AUTOINCREMENT,booking_code TEXT UNIQUE NOT NULL,booking_date TEXT NOT NULL,booking_time TEXT NOT NULL,players INTEGER NOT NULL CHECK(players BETWEEN 1 AND 4),total_cents INTEGER NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT NOT NULL,notes TEXT DEFAULT '',payment_method TEXT NOT NULL CHECK(payment_method IN ('arena','online')),payment_status TEXT NOT NULL DEFAULT 'pending',stripe_session_id TEXT,status TEXT NOT NULL DEFAULT 'confirmed',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE INDEX IF NOT EXISTS idx_bookings_slot ON bookings(booking_date,booking_time,status);`);
const schedule={3:['17:00','17:45','18:30','19:15'],5:['17:30','18:15','19:00','19:45','20:30','21:15'],6:['17:30','18:15','19:00','19:45','20:30','21:15'],0:['17:30','18:15','19:00','19:45','20:30','21:15']};
function validSlot(d,t){const x=new Date(`${d}T12:00:00`);return !Number.isNaN(x.getTime())&&(schedule[x.getDay()]||[]).includes(t)}
function totalFor(p){return p===1?2500:p*2000} function code(){return'A43-'+Math.random().toString(36).slice(2,7).toUpperCase()+'-'+Date.now().toString().slice(-5)}
function expire(){db.prepare(`UPDATE bookings SET status='expired' WHERE status='pending_payment' AND datetime(created_at)<datetime('now','-30 minutes')`).run()}
function occupied(d,t){expire();return Number(db.prepare(`SELECT COALESCE(SUM(players),0) used FROM bookings WHERE booking_date=? AND booking_time=? AND status IN ('confirmed','pending_payment')`).get(d,t).used||0)}
app.post('/api/stripe/webhook',express.raw({type:'application/json'}),(req,res)=>{if(!stripe||!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).send('Stripe non configurato');let event;try{event=stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET)}catch(e){return res.status(400).send('Webhook Error: '+e.message)}const s=event.data.object,c=s.metadata?.booking_code;if(c&&event.type==='checkout.session.completed')db.prepare(`UPDATE bookings SET payment_status='paid',status='confirmed' WHERE booking_code=?`).run(c);if(c&&event.type==='checkout.session.expired')db.prepare(`UPDATE bookings SET status='expired' WHERE booking_code=? AND payment_status!='paid'`).run(c);res.json({received:true})});
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
app.get('/api/availability',(req,res)=>{const date=String(req.query.date||''),d=new Date(`${date}T12:00:00`);if(Number.isNaN(d.getTime()))return res.status(400).json({error:'Data non valida'});res.json({date,slots:(schedule[d.getDay()]||[]).map(time=>({time,available:Math.max(0,4-occupied(date,time))}))})});
const insert=db.prepare(`INSERT INTO bookings(booking_code,booking_date,booking_time,players,total_cents,name,phone,email,notes,payment_method,payment_status,status) VALUES (@booking_code,@booking_date,@booking_time,@players,@total_cents,@name,@phone,@email,@notes,@payment_method,@payment_status,@status)`);const tx=db.transaction(b=>{if(occupied(b.booking_date,b.booking_time)+b.players>4)throw new Error('SLOT_FULL');insert.run(b)});
app.post('/api/bookings',async(req,res)=>{let booking_code;try{const{date,time,players,name,phone,email,notes='',paymentMethod}=req.body||{},p=Number(players),today=new Date(),chosen=new Date(`${date}T12:00:00`);today.setHours(0,0,0,0);if(!validSlot(date,time)||chosen<today)return res.status(400).json({error:'Slot non valido'});if(![1,2,3,4].includes(p))return res.status(400).json({error:'Numero giocatori non valido'});if(!name||!phone||!email)return res.status(400).json({error:'Compila nome, telefono ed email'});if(!['arena','online'].includes(paymentMethod))return res.status(400).json({error:'Metodo di pagamento non valido'});if(paymentMethod==='online'&&!stripe)return res.status(503).json({error:'Pagamento online non ancora collegato a Stripe'});booking_code=code();const total_cents=totalFor(p),online=paymentMethod==='online';tx({booking_code,booking_date:date,booking_time:time,players:p,total_cents,name:String(name).trim(),phone:String(phone).trim(),email:String(email).trim(),notes:String(notes||'').trim(),payment_method:paymentMethod,payment_status:online?'pending':'pay_at_venue',status:online?'pending_payment':'confirmed'});if(online){try{const session=await stripe.checkout.sessions.create({mode:'payment',success_url:`${BASE_URL}/?paid=1&code=${encodeURIComponent(booking_code)}`,cancel_url:`${BASE_URL}/?cancelled=1&code=${encodeURIComponent(booking_code)}`,customer_email:String(email).trim(),expires_at:Math.floor(Date.now()/1000)+1800,metadata:{booking_code},line_items:[{quantity:1,price_data:{currency:'eur',unit_amount:total_cents,product_data:{name:`Virtual Arena 43 — ${p} giocatori — ${date} ${time}`}}}]});db.prepare(`UPDATE bookings SET stripe_session_id=? WHERE booking_code=?`).run(session.id,booking_code);return res.json({ok:true,bookingCode:booking_code,checkoutUrl:session.url})}catch(e){db.prepare(`UPDATE bookings SET status='expired' WHERE booking_code=?`).run(booking_code);throw e}}res.json({ok:true,bookingCode:booking_code})}catch(e){if(e.message==='SLOT_FULL')return res.status(409).json({error:'Non ci sono abbastanza posti disponibili in questo slot'});console.error(e);res.status(500).json({error:'Errore interno'})}});
function adminOK(req){return(req.headers['x-admin-password']||req.query.password||'')===ADMIN_PASSWORD}app.get('/api/admin/bookings',(req,res)=>{if(!adminOK(req))return res.status(401).json({error:'Password admin errata'});expire();res.json(db.prepare(`SELECT id,booking_code,booking_date,booking_time,players,total_cents,name,phone,email,notes,payment_method,payment_status,status,created_at FROM bookings ORDER BY booking_date,booking_time,created_at`).all())});app.patch('/api/admin/bookings/:id/cancel',(req,res)=>{if(!adminOK(req))return res.status(401).json({error:'Password admin errata'});db.prepare(`UPDATE bookings SET status='cancelled' WHERE id=?`).run(req.params.id);res.json({ok:true})});app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));app.listen(PORT,()=>console.log(`Virtual Arena 43 attiva su ${BASE_URL}`));